###############################
############ROUTERS############
###############################
[http.routers]
  [http.routers.${SERVICE}]
    entryPoints = ["websecure"]
    rule = "Host(`${CFG_HOST}`)"
    service = "${SERVICE}"
    middlewares = [ "auth_${SERVICE}"]
    [http.routers.${SERVICE}.tls]
      certResolver = "prod"

###############################
###########SERVICES############
###############################
[http.services]
  [http.services.${SERVICE}.loadBalancer]
    [[http.services.${SERVICE}.loadBalancer.servers]]
      url = "http://localhost:${CFG_PORT}/"


###############################
##########MIDDLEWARES##########
###############################

[http.middlewares]
  [http.middlewares.auth_${SERVICE}.basicAuth]
  users = [
    "${CFG_ADMIN_PWD_HASH}",
  ]
